# Generated by Django 5.0.7 on 2024-08-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default=django.db.models.deletion.SET_NULL, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
